steps:
  - name: gcr.io/cloud-builders/git
    args: ['clone', '--recurse-submodules', '--depth', '1', 'https://github.com/gcushen/hugo-academic.git', 'themes/academic']
  - name: klakegg/hugo:ext-debian
    env: ['HUGO_DESTINATION=/workspace/public']
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy']
